---
stages:
  - tests

run tests:
  stage: tests
  image: golang:1.17-alpine
  cache:
    - key:
        files:
          - go.sum
        prefix: $CI_JOB_IMAGE
      paths:
        - .go-cache/
  script:
    - export GOMODCACHE=$PWD/.go-cache
    - apk add --no-cache git make gcc musl-dev
    - go mod download
    - make test-race test-coverage test-bench
  coverage: '/Code coverage: [0-9.]+/'
  artifacts:
    reports:
      junit: test/tests.xml
      cobertura: test/coverage.xml
